### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by wassupnari** [felipecsl/GifImageView#23]
Hi @felipecsl 

Thanks for providing an awesome library!

I started using `GifImageView` for a few weeks, but I'm getting a crash report which is caused from:

```Caused by: java.lang.UnsatisfiedLinkError: Couldn't load pl_droidsonroids_gif from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myapp.team-1.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]: findLibrary returned null
       at java.lang.Runtime.loadLibrary(Runtime.java:358)
       at java.lang.System.loadLibrary(System.java:533)
       at pl.droidsonroids.gif.GifInfoHandle.(GifInfoHandle.java:40)
       at pl.droidsonroids.gif.GifDrawable.(GifDrawable.java:145)
       at pl.droidsonroids.gif.GifDrawable.(GifDrawable.java:83)
       at pl.droidsonroids.gif.GifViewUtils.setResource(GifViewUtils.java:49)
       at pl.droidsonroids.gif.GifViewUtils.getResourceId(GifViewUtils.java:35)
       at pl.droidsonroids.gif.GifViewUtils.initImageView(GifViewUtils.java:22)
       at pl.droidsonroids.gif.GifImageView.(GifImageView.java:41)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377)
       at android.app.Activity.setContentView(Activity.java:1997)
       at com.myapp.team.activity.intro.SplashAnimScreen.onCreate(SplashAnimScreen.java:71)
       at android.app.Activity.performCreate(Activity.java:5312)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2541)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2641)
       at android.app.ActivityThread.access$800(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5867)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
       at dalvik.system.NativeStart.main(NativeStart.java)```

Any thoughts?

Thanks,
Nari

**Comment by felipecsl** [comment]
It seems like you're using the wrong GifImageView. The namespace `pl.droidsonroids.gif.GifImageView` doesn't belong to this library.

**Comment by wassupnari** [comment]
Oops, sorry about that!
