### ISSUE TITLE
ANR exception in Google Play console. 

### ISSUE THREAD

**Issue by annakozy2011** [felipecsl/GifImageView#49]
I am using your framework for Titanium through intermediate module, and I am getting a lot of these exceptions in Google Play console:

java.lang.ArithmeticException: divide by zero
	at com.felipecsl.gifimageview.library.GifDecoder.advance(GifDecoder.java:229)
	at com.felipecsl.gifimageview.library.GifImageView.run(GifImageView.java:157)
	at java.lang.Thread.run(Thread.java:818)

Could you check it please?

**Comment by felipecsl** [comment]
This has been already fixed on #29
