### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by wingsZz** [felipecsl/GifImageView#68]
when gif is loading ,i change the wifi to 4G,and then app crash.
java.lang.NullPointerException: Attempt to write to field 'int com.felipecsl.gifimageview.library.GifHeader.status' on a null object reference
at com.felipecsl.gifimageview.library.GifHeaderParser.setData(GifHeaderParser.java:62)
at com.felipecsl.gifimageview.library.GifDecoder.read(GifDecoder.java:513)
at com.felipecsl.gifimageview.library.GifImageView.setBytes(GifImageView.java:55)
at com.felipecsl.gifimageview.app.MainActivity$3.onPostExecute(MainActivity.java:60)
at com.felipecsl.gifimageview.app.MainActivity$3.onPostExecute(MainActivity.java:58)

**Comment by felipecsl** [comment]
Can you please attach an example GIF image to help reproduce this issue? Also which Android version are you using?

**Comment by felipecsl** [comment]
Closed due to inactivity
